AWSTemplateFormatVersion: '2010-09-09'
Description: Creates SSL Certificate, S3 bucket for static webcontent and a route53 DNS record
Parameters:
  DomainName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone e.g. example.de
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
Resources:
  WebsiteCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref 'DomainName'
      SubjectAlternativeNames: [!Ref 'DomainName',!Join ['.',['*',!Ref 'DomainName']]]
      ValidationMethod: DNS
Outputs:
  DomainName:
    Value: !Ref 'DomainName'
    Export:
      Name: "DomainName"
  